POST http://localhost:3003/api/blogs 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlN1cGVyVGVzdGVyIiwiaWQiOiI2MDFkMzEwNWNlZWIxZDQzZGQzOWMyOTAiLCJpYXQiOjE2MTI1MjU4NjR9.pl8es5qjEUXfrpF-7-eiKOpccSjSu86acnyEkDIsdBY

{
    "title": "How to clean your room",
    "author": "Cleany Cleaner",
    "url": "cleanhouse.com",
    "likes": 154
}